res_callback(
  [{
  id: 1,
  "location":{"lat":10.318136,"lng":123.897055},
  "name": "Pedro's Ihawan",
  "type": ["barbeque","ihawan"],
  "address": "54 M.F. Escario, Cebu City",
  "bestseller": ["Inihaw na Manok", "Inihaw na Liempo"],
  "rating": 4.1,
  "reviews": ["Very accommodating staff","Delicious foods! Sarap!","10/10 will come back again."]
},
{ id: 2,
  "location":{"lat":10.315925,"lng":123.893788},
  "name": "Juan's Ihawan",
  "type": ["barbeque","ihawan"],
  "address": "107-111 Juana Osmeña St, Cebu City",
  "bestseller": ["Inihaw na Baka", "Inihaw na Liempo"],
  "rating": 5.0,
  "reviews": ["Best Place ever!","5 star restaurant","Very clean and neat, next to God","Yes to this","Comeback again!","5 star is true","Mang ina-who??","Go go go!! More more foodie",
  "Kumain kami dito ng family ko. Ang babait ng staff and magalang, yung manager din accommodating. Sila yung nag asikaso samin nung naghahanap kami ng upuan para sa baby namin. I highly recommend dito kayo kumain kasama mga mahal niyo sa buhay. Sulit ang bayad pati ang oras niyo sa byahe.",
  "Yes to this place! I like the vibe and the place, very homey.","Keep it up. Whatever they may say, you are good, never doubt yourself. Find someone who will value your worth."]
},
{ id: 3,
  "location":{"lat":10.317172,"lng":123.889869},
  "name": "Fiona Catering",
  "type": ["catering", "filipino"],
  "address": "Don Gil Garcia St, Cebu City",
  "bestseller": ["Tinolang Manok"],
  "rating": 2.1,
  "reviews": ["Fiona is very nice"]
},
{ id: 4,
  "location":{"lat":10.317013,"lng":123.885867},
  "name": "Shrek Mexican Resto",
  "type": ["mexican"],
  "address": "11-d M. Veloso St, Cebu City",
  "bestseller": ["Nacho Cheese"],
  "rating": 3.1,
  "reviews": []
},
{ id: 5,
  "location":{"lat":10.309840,"lng":123.893167},
  "name": "Rotonda-rounda-world",
  "type": ["international"],
  "address": "Capitol Site, Cebu City",
  "bestseller": ["Lamb Skewers", "Roast Beef"],
  "rating": 4.3,
  "reviews": ["Legit food", "Walang tapon"]
},
{ id: 6,
  "location":{"lat":10.302160,"lng":123.895658},
  "name": "Atay Balunan Kayo Jan",
  "type": ["barbeque","ihawan"],
  "address": "R. Landon Ext, Cebu City",
  "bestseller": ["Chicken Isaw"],
  "rating": 0.0,
  "reviews": ["Malapit sa.."]
},
{ id: 7,
  "location":{"lat":10.305448,"lng":123.890734},
  "name": "Barangay Carinderia",
  "type": ["filipino","catering"],
  "address": "Tambis St., Cebu City",
  "bestseller": ["Lechon Paksiw"],
  "rating": 2.3,
  "reviews": ["Cheap food"]
},
{ id: 8,
  "location":{"lat":10.317766,"lng":123.884704},
  "name": "G.I. Joe Food",
  "type": ["american","catering"],
  "address": "V Rama Ave, Cebu City",
  "bestseller": ["Cheeseburger","Hamburger","New York's Pizza"],
  "rating": 4.5,
  "reviews": ["Putokbatok!","Worth your money and time"]
},
{ id: 9,
  "location":{"lat":10.325970,"lng":123.879729},
  "name": "Pitzerria",
  "type": ["italian"],
  "address": "Guadalajara, Cebu City",
  "bestseller": ["Ham and Cheese Pizza"],
  "rating": 3.3,
  "reviews": ["Cheap pizza"]
},
{ id: 10,
  "location":{"lat":10.316796,"lng":123.888669},
  "name": "Isadaan sa Guada",
  "type": ["fish","ihawan"],
  "address": "74 M. Velez St, Cebu City",
  "bestseller": ["Inihaw na Tilapia"],
  "rating": 1.4,
  "reviews": ["No","Unaccommodating staff"]
},
{ id: 11,
  "location":{"lat":10.314849,"lng":123.895295},
  "name": "Oppa's Kitchen",
  "type": ["korean","barbeque"],
  "address": "181D Maria Christina Ext St, Cebu City",
  "bestseller": ["Yangnyum Chicken", "Samgyupsal"],
  "rating": 4.7,
  "reviews": ["Daming Oppa","Yes to Samgyups!"]
},
{ id: 12,
  "location":{"lat":10.312183,"lng":123.898573},
  "name": "Lutong Bahay ni Bah",
  "type": ["filipino","catering"],
  "address": "Kamputhaw, Cebu City, Cebu",
  "bestseller": ["Adobong Manok", "Sinigang na Baboy", "Sinigang na Manok"],
  "rating": 1.8,
  "reviews": ["Luto ka na lang sa bahay niyo 1.0 star"]
}]);
